// <auto-generated />
namespace TaxCalculator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class zonenavigationaddedtocitizen2withZoneIdFieldaddition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(zonenavigationaddedtocitizen2withZoneIdFieldaddition));
        
        string IMigrationMetadata.Id
        {
            get { return "201902211248408_zone navigation added to citizen 2 with ZoneId Field addition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
