// <auto-generated />
namespace TaxCalculator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class lastfiscalyearfieldsaddedtolandtaxvaluation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lastfiscalyearfieldsaddedtolandtaxvaluation));
        
        string IMigrationMetadata.Id
        {
            get { return "201903120823328_last fiscal year fields added to land tax valuation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
