// <auto-generated />
namespace TaxCalculator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class housetaxidaddedtolandtaxhistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(housetaxidaddedtolandtaxhistory));
        
        string IMigrationMetadata.Id
        {
            get { return "201902250821285_house tax id added to land tax history"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
