// <auto-generated />
namespace TaxCalculator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class additionoffiscalyeartovaluationtables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(additionoffiscalyeartovaluationtables));
        
        string IMigrationMetadata.Id
        {
            get { return "201903110223089_addition of fiscal year to valuation tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
