// <auto-generated />
namespace TaxCalculator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class zoneidaddedtocitizen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(zoneidaddedtocitizen));
        
        string IMigrationMetadata.Id
        {
            get { return "201902211224330_zoneid added to citizen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
