// <auto-generated />
namespace TaxCalculator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class citizenadedtolandtaxhistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(citizenadedtolandtaxhistory));
        
        string IMigrationMetadata.Id
        {
            get { return "201902230942004_citizen aded to landtax history"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
