// <auto-generated />
namespace TaxCalculator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class specific2taxhistoryidadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(specific2taxhistoryidadded));
        
        string IMigrationMetadata.Id
        {
            get { return "201904110315453_specific 2 taxhistory id added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
